### ISSUE TITLE
today's predictions

### ISSUE THREAD

**Issue by vogali** [sidharthrajaram/mvp-predict#1]
How do you do today's predictions?

**Comment by vogali** [comment]
how do you calculate the percentage of 29%? I cannot find the code~~~

**Comment by sidharthrajaram** [comment]
Hey, @vogali I'll answer your second question first: my code looks at 7 stats (PPG, PER, PPG+RPG+APG, etc.) and figures out which two players are most alike _and_ above the mvp benchmark for that stat. The "mvp benchmark" is compiled from a weighted average of all MVPs since 2000. So this means upon running, there will be a total of 14 players shown to me. 

I then just sum up occurrences of each player in this total list and divide that sum by 14 (and multiply by 100) to get the percentage. Essentially the more frequently a player meets or exceeds the MVP benchmark, the higher their probability.

I thought the implementation of this last step would be incredibly trivial so I just figured I can do the simple division by myself. But yes, it would be optimal if I included the division in my code.

**Comment by sidharthrajaram** [comment]
As for your first question, I simply run the program each day (or every couple of days). I look at players' occurrences and can calculate the probability. I attached a picture of today's group of 14. For each stat, there's one player who is closest to the benchmark and one who is most above. VORP is a seasonal stat as opposed to a per game one so the player happens to be the same.

<img width="698" alt="screen shot 2018-03-12 at 4 30 11 pm" src="https://user-images.githubusercontent.com/14987538/37314728-eb65bda6-2612-11e8-8e07-56b37e9509ee.png">
